demo1/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'', include('mysqldemo.urls', namespace='mysqldemo')),
]
app_name = 'mysqldemo'

mysqldemo/urls.py
"""定义mysqldemo的URL模式"""
from django.conf.urls import url
from django.urls import path
from mysqldemo import views
from django.urls import re_path

urlpatterns = [
    # 主页
    # url django1.x的写法
    # url(r'^show_info/$', views.show_info, name='show_info'),
    # url(r'^add_stu/$', views.add_stu, name='add_stu'),
    # url(r'^del_stu/(?P<id>\d+)/$', views.del_stu, name='del_stu'),
    # url(r'^mod_stu/(?P<id>\d+)/$', views.mod_stu, name='mod_stu'),
    # url(r'^sel_stu/$', views.sel_stu, name='sel_stu'),
    # path是django2.x的写法，re_path与上面正则写法一样
    path('show_info/', views.show_info, name='show_info'),
    path('add_stu/', views.add_stu, name='add_stu'),
    re_path('^del_stu/(\\d+)/$', views.del_stu, name='del_stu'),
    re_path('^mod_stu/(\\d+)/$', views.mod_stu, name='mod_stu'),
    path('sel_stu/', views.sel_stu, name='sel_stu'),
]

app_name = 'mysqldemo'

mysqldemo/models.py
from django.db import models


# Create your models here.
class Vps(models.Model):
    hostname = models.CharField(max_length=50)
    ip = models.CharField(max_length=50)
    memory = models.CharField(max_length=50)
    cpu = models.CharField(max_length=20)

    def __str__(self):
        return self.hostname

    class Meta:
        db_table = 'vps'

mysqldemo/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from mysqldemo.models import Vps


# Create your views here.
# from mysqldemo.models import User


def show_info(request):
    if request.method == 'GET':
        # 获取所有数据
        vpss = Vps.objects.all()
        return render(request, 'info.html', {'vpss': vpss})


def add_stu(request):
    if request.method == 'GET':
        vpss = Vps.objects.all()
        return render(request, 'add.html', {'vpss': vpss})
    if request.method == 'POST':
        # 括号里的都是从html里获取到的 name="hostname">
        hostname = request.POST.get('hostname')
        ip = request.POST.get('ip')
        memory = request.POST.get('memory')
        cpu = request.POST.get('cpu')
        # 插入数据库
        Vps.objects.create(hostname=hostname, ip=ip, memory=memory, cpu=cpu)
        return HttpResponseRedirect(reverse('mysqldemo:show_info'))


def del_stu(request, id):
    if request.method == 'GET':
        # .delete()删除操作
        Vps.objects.get(pk=id).delete()
        return HttpResponseRedirect(reverse('mysqldemo:show_info'))


def mod_stu(request, id):
    if request.method == 'GET':
        vps = Vps.objects.get(pk=id)
        return render(request, 'mod.html', {'vps': vps})
    if request.method == 'POST':
        hostname = request.POST.get('hostname')
        ip = request.POST.get('ip')
        memory = request.POST.get('memory')
        cpu = request.POST.get('cpu')
        Vps.objects.filter(pk=id).update(hostname=hostname, ip=ip, memory=memory, cpu=cpu)
        return HttpResponseRedirect(reverse('mysqldemo:show_info'))


def sel_stu(request):
    if request.method == 'GET':
        return render(request, 'sel.html')
    if request.method == 'POST':
        hostname = request.POST.get('hostname')
        try:
            vps = Vps.objects.get(hostname=hostname)
            return render(request, 'sel.html', {'vps': vps})
        except:
            return render(request, 'sel.html', {'error': '该虚拟机不存在'})

mysqldemo/templates/add.html
{% extends 'base.html' %}
{% block content %}
    <table align="center">
    <tr>
    <form action="" method="post">
        {% csrf_token %}
        <td>主机名：<input type="text" name="hostname"></td>
        <td>ip地址：<input type="text" name="ip"></td>
        <td>内存：<input type="text" name="memory"></td>
        <td>cpu：<input type="text" name="cpu">&nbsp;</td>
        <td><input type="submit" value="提交" style="width: 100px"></td>
    </form>
    </tr>
    </table>
{% endblock %}

mysqldemo/templates/base.html
<style>
    /*设置按钮大小*/
    button{width: 200px;height: 50px;font-size: 20px}
</style>
<p align="center">
  <a href="{% url 'mysqldemo:show_info' %}"><button>显示所有数据</button></a>
</p>

{% block content %}{% endblock %}

mysqldemo/templates/info.html
{% extends 'base.html' %}
{% block content %}
<style>
    /*设置按钮大小*/
    button{width: 200px;height: 50px;font-size: 20px}
</style>
<table align="center">
    <tr>
    <td><a href="{% url 'mysqldemo:add_stu' %}">{{ vps.id }}<button>新增虚拟机信息</button></a>&emsp;&emsp;</td>
    <td><a href="{% url 'mysqldemo:sel_stu' %}">{{ vps.id }}<button>查询虚拟机信息</button></a></td>
    </tr>
</table>
    <br>
<table border="1" align="center">
    <thead>
        <th align="center" style="color:red">&nbsp;序号&nbsp;</th>
        <th align="center" style="color:red">&emsp;主机名&emsp;</th>
        <th align="center" style="color:red">&emsp;&emsp;IP地址&emsp;&emsp;</th>
        <th align="center" style="color:red">&emsp;内存&emsp;</th>
        <th align="center" style="color:red">&emsp;CPU&emsp;</th>
        <th align="center" style="color:red">删除虚拟机</th>
        <th align="center" style="color:red">修改虚拟机</th>
    </thead>
    <tbody>
        {% for vps in vpss %}
            <tr>
                <td align="center">{{vps.id}}</td>
                <td align="center">{{vps.hostname}}</td>
                <td align="center">{{vps.ip}}</td>
                <td align="center">{{vps.memory}}</td>
                <td align="center">{{vps.cpu}}</td>
                <td align="center"><a href="{% url 'mysqldemo:del_stu' vps.id %}">
                    <button style="width: 80px;height: 30px;font-size: 18px">删除</button></a></td>
                <td align="center"><a href="{% url 'mysqldemo:mod_stu' vps.id %}">
                    <button style="width: 80px;height: 30px;font-size: 18px">修改</button></a></td>
            </tr>
        {% endfor %}
    </tbody>
</table>


{% endblock %}

mysqldemo/templates/mod.html
{% extends 'base.html' %}
{% block content %}
<table align="center">
    <tr>
    <form action="" method="post">
        {% csrf_token %}
       <td>主机名： <input type="text" name="hostname" value="{{vps.hostname}}"></td>
       <td>IP地址： <input type="text" name="ip" value="{{vps.ip}}"></td>
       <td>内存： <input type="text" name="memory" value="{{vps.memory}}"></td>
       <td>CPU： <input type="text" name="cpu" value="{{vps.cpu}}"></td>
        <td><input type="submit" value="修改" style="width: 100px;font-size: 15px"></td>
    </form>
    </tr>
</table>
{% endblock %}

mysqldemo/templates/sel.html
{% extends 'base.html' %}
{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        <table align="center">
            <tr>
            <td><h3>请输入主机名:<input type="text" name="hostname"></h3></td>
                <td><h3><input type="submit" value="提交" style="width: 100px;
                height: 28px;font-size: 18px"></h3></td>
            </tr>
        </table>
        <table border="1" align="center">
            <br>
        {% if vps %}
            <thead>
            <th align="center" style="color:red">&nbsp;序号&nbsp;</th>
            <th align="center" style="color:red">&emsp;主机名&emsp;</th>
            <th align="center" style="color:red">&emsp;&emsp;IP地址&emsp;&emsp;</th>
            <th align="center" style="color:red">&emsp;内存&emsp;</th>
            <th align="center" style="color:red">&emsp;CPU&emsp;</th>
            </thead>
            <tbody>
                <tr>
                    <td align="center">{{vps.id}}</td>
                    <td align="center">{{vps.hostname}}</td>
                    <td align="center">{{vps.ip}}</td>
                    <td align="center">{{vps.memory}}</td>
                    <td align="center">{{vps.cpu}}</td>
                </tr>
            </tbody>
        </table>
        {% endif %}
    </form>
<h1 style="color:red" align="center">{{error}}</h1>
{% endblock %}